import Navigation from './Navigation'
import Box from '@mui/material/Box'
import { useSession } from 'next-auth/react'
import FeedbackPopup from './FeedbackPopup'
import NotificationPopup from './NotificationPopup'
import BodyColumn from './BodyColumn'
import ProfileMenu from './ProfileMenu'
import { useRouter } from 'next/router'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const {status} = useSession();
  const router = useRouter();
  if (status == "loading") return;
  if (status == "unauthenticated") {
    if (router.pathname != "/") router.push("/")
    return (
    <>{children}</>
  )
  }
  return (
    <Box sx={{ display: 'flex'}}>
      <Navigation/>
        <BodyColumn>
          {children}
          <ProfileMenu />
          <NotificationPopup />
          <FeedbackPopup />
        </BodyColumn>
    </Box>
  )
}
